### PR TITLE
User Story 1624627 - Rebranding for Azure Machine Learning

### PR DESCRIPTION
**Pull request by craigcaseyMSFT**
Rebranding of Azure Machine Learning service per https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1624627

### CODE REVIEW

**Comment by craigcaseyMSFT** [comment]
@PeterCLu - Hi, Peter. This repo is ready to review. Please let me know if we're OK to merge. Thanks!

**Comment by PeterCLu** [comment]
@craigcaseyMSFT looks good!

**Comment by craigcaseyMSFT** [comment]
#sign-off

**Comment by craigcaseyMSFT** [comment]
Hi @mx-iao  - Thanks for your approval. Would you be able to merge this PR for me? Or if not, please let me know who I should contact? Thank you!

**Comment by mx-iao** [comment]
Merged

**Comment by craigcaseyMSFT** [comment]
Hi, @diondrapeck  - I see that you have merge perms in this repo. Would you be able to merge this PR for me? It is part of a rebranding effort we are doing for Azure Machine Learning. I have obtained the necessary approvals.

If not, please let me know who I should contact? Thank you for your help!

**Pull request merged**
